// Recontres
export const GET_RENCONTRES_SUCCESS = "GET_RENCONTRES_SUCCESS";
// Recontre
export const AJOUT_RENCONTRE = "AJOUT_RENCONTRE";
export const POST_RENCONTRE = "POST_RENCONTRE";
export const POST_RENCONTRE_SUCCESS = "POST_RENCONTRE_SUCCESS";
export const GET_RENCONTRE_SUCCESS = "GET_RENCONTRE_SUCCESS";
export const PUT_RENCONTRE_SUCCESS = "PUT_RENCONTRE_SUCCESS";
export const DEL_RENCONTRE_SUCCESS = "DEL_RENCONTRE_SUCCESS";
export const NOUVELLE_MARQUE = "NOUVELLE_MARQUE";